openapi: '3.0.3'

info:
  title: Sample-API-Backend
  version: '1.0'

servers:
  - url: http://localhost:3001
    description: Local Development Server

components:
  schemas:
    SuccessfulResponseMessage:
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
    SuccessfulResponseReturn:
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          description: dynamic entity (eg. token, queried object)
    CommonError:
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Missing required field/s
    User:
      description: User entity schema
      properties:
        username: 
          type: string
          description: Entity immutable primary key
        password:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string

paths:
  /user/{id}:
    get:
      tags:
        - "General"
      description: Look for a user
      parameters:
        - in: path
          name: username 
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Response 
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean 
                  data:
                    type: object
                    properties:
                      username:
                        type: string
                      password:
                        type: string
        
        '404':
          description: ""
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean 
                  message:
                    type: string
            
                      
  /user/:
    post:
      tags:
        - "General"
      description: Create a new User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string 
              required:
                - "username"
                - "password"
      responses:
        "201":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        "404":
          description: Failed Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean

tags:
  - name: General
